apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-bluetooth-dev-bluetooth-module-inventory
  namespace: bluetooth-cicd
spec:
  encryptedData:
    webhook-secret-key: AgA3xEbNA8v751sRDYeraAGTzcJVlwGWszg3JObbkYX32z6ToJQrhQ28+r5z75goPL5m+L1ATlz9oJ8NZVxuKNSjIvQTtkqFBYoyzzWZX7VI6e0aYxDM4YUdPVLyxNHCN/ulJFUo6LOBaEK6c71RC+odXbnx6fwr574ILZmvVZuGJMbP4lB/9n3j8vdosEc0xoywoSlopdkXEXtSVNuqXQwb7BTZqU3j9h1A02Y9BXJoHlLAgoPFXHXluVYR5z2mlUuiteF/aaUWJuEqSFTwZA/QyQR5ReCe7YvMtbyf5ZeOv6yT9u5kHN75NK0mRfjhEDo74hRrzmUOlWIuAHQYpD0u8JaZhrN7z691UOqWvk+DJdsMiIkWDX8CMvZpKp05ScVGe1NSLlP4iEubu/2giONJjG22DAt7qeB4Y1AYLTqpEkEZTKcpAFpTvzOHDfuD6uHz9vDLmLVbcjwbEp/QaTSB8B3EeO7YrQWbd5WRU+6EpoBpeA0FaExkW44VWBYvz+K6gysyQAuT/nH8etznISOJ2IqLJ97VXducHA3/ti61exNWGlZHBGY0IQEqIJUqfkEuXUBbljyezdHqnfU2j1ViVVRDfUVCrVvJc97xJ70BL8VHBau3LXNU5EBgb9Qk9wxaPtOJwTy8jcS3/bpNJX5w1kZJGl9tP2y76kBERvlM6JzMB/+bHH7ukx51CI09cG4C0lWDa4vcQCKzFes+RHLm0X2/Gw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-bluetooth-dev-bluetooth-module-inventory
      namespace: bluetooth-cicd
    type: Opaque
status: {}
